# Generated by Django 3.2.4 on 2021-07-02 03:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 3, 57, 50, 270053, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
