# Generated by Django 3.2.7 on 2021-09-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='timeStamp',
        ),
    ]
