# Generated by Django 3.2.7 on 2021-09-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('update_desc', models.CharField(default='', max_length=300)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
