# Generated by Django 3.2.7 on 2021-09-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blogpost_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('heading1', models.CharField(max_length=300)),
                ('content1', models.CharField(max_length=5000)),
                ('heading2', models.CharField(max_length=300)),
                ('content2', models.CharField(max_length=5000)),
                ('heading3', models.CharField(max_length=300)),
                ('content3', models.CharField(max_length=5000)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
